package dev.wycor.pirates.game;

public enum Treasure {
    EMERALD_OF_HOPE,
    GOLDEN_SWORD_OF_YR,
    KING_FLYNNS_ROYAL_SCEPTRE,
    SACRED_ONYX_CROSS,
    LOST_PEARL_OF_JEHVA,
    QUEEN_LATHAS_CROWN,
    RUBY_RING_OF_POWER,
    SILVER_CHALICE_OF_AUNGE,
    MURPHYS_CHEST_OF_GOLD,
    QUEEN_LATHAS_NECKLACE
}
